FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y motion && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY motion.conf /etc/motion/motion.conf

EXPOSE 100

ENTRYPOINT ["motion", "-n", "-c", "/etc/motion/motion.conf"]